sudo: false

language: node_js

node_js:
    - "5"
    - "4"
    - "0.12"
    - "0.10"

before_install:
    - if [ "$TRAVIS_NODE_VERSION" = "0.10" ]; then npm install -g npm@2; fi

matrix:
    fast_finish: true
